### ISSUE TITLE
jcenter停服了 

### ISSUE THREAD

**Issue by 3c** [umeng/MultiFunctionAndroidMavenDemo-master#2]
```https://dl.bintray.com/umsdk/release```

该换一换了 否则build不过去

**Comment by DevYJQ** [comment]
运行时报403 Forbidden，只能改成手动集成了吗？

**Comment by trycatchx** [comment]
+1

**Comment by 3c** [comment]
```maven { url 'https://repo1.maven.org/maven2/' } ```

文档更新了  关闭
